version: '3'

tasks:
  default:
    - task: tidy
    - task: lint
    - task: test

  test:
    cmds:
      # - go test ./... -race
      - go test ./...

  lint:
    cmds:
      - golangci-lint run

  tidy:
    cmds:
      - go mod tidy

  cov:
    cmds:
      - mkdir -p temp
      - go test -coverprofile=temp/coverage.out ./...
      - go tool cover -html=temp/coverage.out
