version: '3'

tasks:
  default:
    - task: test
    - task: lint
    - task: tidy

  test:
    cmds:
      # - go test ./... -race
      - go test ./...

  lint:
    cmds:
      - golangci-lint run

  tidy:
    cmds:
      - go mod tidy
