name: main

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.ref }}

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: "1.17"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          skip-go-installation: true

      - name: Run tests
        shell: bash
        run: |
          go test ./...

  docker:
    runs-on: ubuntu-latest
    needs:
      - lint-test
    env:
      REGISTRY_NAME: quay.io
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY_NAME }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Choose tag
        id: tag
        shell: bash
        run: echo "::set-output name=TAG::${GITHUB_REF_NAME//\//-}"

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.REGISTRY_NAME }}/${{ github.repository }}:${{ steps.tag.outputs.TAG }}
